Repository lh-rubz/GSG_Cinema, pull requests merged in 2025-04, with the labels that each got.

#17 16 implement cast and director page
  app/cast/[id]/page.tsx
  app/director/[id]/page.tsx
  types/types.ts
Labels: enhancement, new feature

#18 6 fixing light and dark mode
  app/globals.css
  app/layout.tsx
  app/not-found.tsx
  app/providers.tsx
  components.json
  components/landing-footer.tsx
  components/landing-header.tsx
  components/theme-provider.tsx
  components/theme-toggle.tsx
  lib/utils.ts
  package-lock.json
  package.json
  tailwind.config.ts
  types/types.ts
Labels: bug

#23 Create promotions page with components and date formatting
  app/layout.tsx
  app/promotions/page.tsx
  components/promotionCard.tsx
  components/promotionsContainer.tsx
  data/promotions.ts
  functions.ts
  package-lock.json
  package.json
  tailwind.config.ts
  types/types.ts
Labels: enhancement, new feature

#27 implement profile page
  app/profile/page.tsx
  app/tickets/components/ticket.tsx
  app/tickets/page.tsx
  package-lock.json
  tailwind.config.ts
Labels: enhancement, new feature

#42 41 Add liked, reply ,and review features
  app/api/movies/[id]/route.ts
  app/movies/[id]/components/review-card.tsx
  app/movies/[id]/components/review-form.tsx
  app/movies/[id]/components/review-tab.tsx
  app/movies/[id]/page.tsx
  package-lock.json
  package.json
Labels: new feature

#48 Update styling and add admin functionality
  app/about/page.tsx
  app/admin/page.tsx
  app/api/sendEmail/assets/CinemaHubLogo.png
  app/api/sendEmail/route.ts
  app/contact/page.tsx
  app/faq/page.tsx
  app/globals.css
  app/layout.tsx
  app/movies/[id]/components/info-tab.tsx
  app/movies/[id]/components/movie-cast.tsx
  app/movies/[id]/components/movie-header.tsx
  app/movies/[id]/components/movie-tabs.tsx
  app/movies/[id]/components/review-card.tsx
  app/movies/[id]/components/review-form.tsx
  app/movies/[id]/components/review-tab.tsx
  app/movies/[id]/components/showtime-card.tsx
  app/movies/[id]/components/showtimes.tsx
  app/movies/[id]/components/star-rating.tsx
  app/movies/[id]/components/trailer.tsx
  app/movies/[id]/error.tsx
  app/movies/[id]/page.tsx
  app/movies/page.tsx
  app/page.tsx
  app/terms/page.tsx
  components/activity-item.tsx
  components/conditonalLayout.tsx
  components/hero-section.tsx
  components/movies-filters.tsx
  components/moviesCard.tsx
  components/user-fab.tsx
  package-lock.json
  package.json
Labels: bug

#53 fix the dark mode in staff pages
  app/staff/layout.tsx
  app/staff/movies/page.tsx
  app/staff/page.tsx
  app/staff/tickets/page.tsx
Labels: Fixes
